# Generated by Django 4.2.4 on 2023-08-16 10:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_contact_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
