# Generated by Django 4.2.4 on 2023-08-21 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_contact_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_image', models.ImageField(upload_to='Blog')),
                ('blog_name', models.TextField()),
                ('blog_desc', models.CharField(max_length=100)),
            ],
        ),
    ]
