# Generated by Django 4.2.4 on 2023-09-01 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_view_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
