# Generated by Django 4.2.4 on 2023-09-01 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_blog_blog_view_count_alter_contact_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='blog_view_count',
        ),
    ]
