# Generated by Django 4.2.4 on 2023-09-04 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_blog_blog_view_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('player_email', models.EmailField(max_length=254, unique=True)),
                ('player_age', models.IntegerField(default=18)),
                ('player_country', models.CharField(max_length=100)),
                ('player_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='playerid', to='home.playerid')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos', to='home.position')),
            ],
            options={
                'verbose_name': 'player',
                'ordering': ['player_name'],
            },
        ),
    ]
