# Generated by Django 4.2.4 on 2023-09-04 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_playerid_position_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specs_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='player',
            name='player_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='playeridx', to='home.playerid'),
        ),
        migrations.CreateModel(
            name='SpecsRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playerrating', to='home.player')),
                ('specs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specsname', to='home.specs')),
            ],
        ),
    ]
