# Generated by Django 4.2.4 on 2023-09-04 09:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_specs_alter_player_player_id_specsrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='specsrating',
            name='rating',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterUniqueTogether(
            name='specsrating',
            unique_together={('player', 'specs')},
        ),
    ]
