# Generated by Django 4.2.4 on 2023-09-29 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_dog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
