# Generated by Django 4.2.4 on 2023-09-29 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_dog_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dog',
        ),
    ]
